<a href="https://colab.research.google.com/github/PlaZMaD/ml_miem_2024/blob/main/Seminar_1%2B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Машинное обучение для построения математических моделей

Добро пожаловать на наш курс!

Команда:
* Фёдор Ратников (лекции)
* Евгений Курбатов (семинары)

### Способы связи с нами

Группа в ТГ

### Семинары
* Используем тетрадки [Google Colab](https://colab.research.google.com)
* Тетрадки текущего и прошедших семинаров [будут лежать здесь](https://github.com/PlaZMaD/ml_miem_2024)
* Будут опросы и задания *допишите код*
* **Активное участие** на семинарах входит в оценку аудиторных занятий

### Домашние задания

 Jupyter-тетрадки (Google Colaboratory) в GitHub

# Семинар 1: Введение в анализ данных

## Python для математического моделирования
Использованы материалы курса: https://cs231n.github.io/python-numpy-tutorial/

NB: Мы всюду используем Python 3.

### Основные типы данных

#### Числовые данные

Целые и числа с плавающей запятой работают примерно так, как вы привыкли в других языках:

In [ ]:
x = 3
print(x, type(x))

In [ ]:
print(x + 1)   # Addition
print(x - 1)   # Subtraction
print(x * 2)   # Multiplication
print(x ** 2)  # Exponentiation

In [ ]:
x += 1
print(x)
x *= 2
print(x)

In [ ]:
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y ** 2)

Обратите внимание, что в отличие от многих языков, в Python нет унарных операторов инкремента (`x++`) или декремента (`x--`).

В Python также есть встроенные типы для длинных целых и комплексных чисел; все подробности вы можете найти в [документации](https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-long-complex).

#### Булевы операторы
Python реализует все стандартные операторы для булевой логики, но использует английские слова, а не символы (&&, || и т.д.):

In [ ]:
t, f = True, False
print(type(t))

Теперь рассмотрим операции:

In [ ]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

#### Строки

In [ ]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter
print(hello, len(hello))

In [ ]:
hw = hello + ' ' + world  # String concatenation
print(hw)

In [ ]:
hw12 = '{} {} {}'.format(hello, world, 12)  # string formatting
print(hw12)

In [ ]:
print('{} is three'.format(3))

In [ ]:
print(f'{3} is three') # f-string is also an option

Строковые объекты имеют множество полезных методов; например:

In [ ]:
s = "hello"
print(s.capitalize())  # Capitalize a string
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces
print(s.center(7))     # Center a string, padding with spaces
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another
print('  world '.strip())  # Strip leading and trailing whitespace

Список всех строковых методов можно найти в [документации](https://docs.python.org/3/library/stdtypes.html#string-methods).

### Контейнеры
Python включает несколько встроенных типов контейнеров:
*   list
*   dictionary
*   set
*   tuple

#### Lists
Список в Python - это эквивалент массива; он имеет изменяемый размер и может содержать элементы разных типов:

In [ ]:
xs = [3, 1, 2]   # Create a list
print(xs, xs[2])
print(xs[-1])     # Negative indices count from the end of the list; prints "2"

In [ ]:
xs[2] = 'foo'    # Lists can contain elements of different types
print(xs)

In [ ]:
xs.append('bar') # Add a new element to the end of the list
print(xs)

In [ ]:
xs += ['foo']
print(xs)

In [ ]:
x = xs.pop()     # Remove and return the last element of the list
print(x, xs)

Как обычно, все подробности о списках вы можете найти в [документации](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists).

#### Срезы

Помимо доступа к элементам списка по одному, Python предоставляет лаконичный синтаксис для доступа к подспискам; это известно как slicing:

In [ ]:
nums = list(range(5))    # range is a built-in function that creates a list of integers
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print(nums)         # Prints "[0, 1, 8, 9, 4]"

#### Циклы

Вы можете перебирать элементы списка следующим образом:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

Если вам нужен доступ к индексу каждого элемента в теле цикла, используйте встроенную функцию `enumerate`:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('{}: {}'.format(idx + 1, animal))

#### List comprehensions

Во время программирования мы часто хотим преобразовать один тип данных в другой. В качестве простого примера рассмотрим следующий код, который вычисляет квадраты чисел:

In [ ]:
%time # измеряет время выполнения кода в ячейке
nums = [0, 1, 2, 3, 4]

squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

Вы можете упростить этот код с помощью cпискового включения:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

Списковые включения могут содержать условия:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

#### Dictionaries
Словарь хранит пары (ключ, значение). Вы можете использовать его следующим образом:

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

In [ ]:
d['fish'] = 'wet'    # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"

In [ ]:
print(d['monkey'])  # KeyError: 'monkey' not a key of d

In [ ]:
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"

Все, что вам нужно знать о словарях, вы можете найти в [документации](https://docs.python.org/3/library/stdtypes.html#dict).

Перебирать ключи в словаре очень просто:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A {} has {} legs'.format(animal, legs))

Cловарные включения похожи на списковые, но позволяют легко строить словари. Например:

In [ ]:
nums = [0, 1, 2, 3, 4, 7, 32]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

print(3 in nums)

#### Sets
Множество - это неупорядоченный набор отдельных элементов. В качестве простого примера рассмотрим следующее:

In [ ]:
animals = {'cat', 'dog', 4}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"
print(5 in animals)

In [ ]:
animals.add('fish')      # Add an element to a set
print('fish' in animals)
print(len(animals))       # Number of elements in a set;

In [ ]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print(animals)
print(len(animals))
animals.remove('cat')    # Remove an element from a set
print(len(animals))

_Циклы_: Итерация по множеству имеет тот же синтаксис, что и итерация по списку; однако, поскольку множества неупорядочены, вы не можете делать предположения о порядке посещения элементов множества:

In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('{}: {}'.format(idx + 1, animal))

Включения множеств. Подобно спискам и словарям, мы можем легко конструировать множества с помощью set comprehensions:

In [ ]:
from math import sqrt
s = {int(sqrt(x)) for x in range(30)}
s = {int(x**0.5) for x in range(30)} # альтернативный способ
print(s)

#### Tuples

Кортеж - это (неизменяемый) упорядоченный список значений. Кортеж во многом похож на список; одно из самых важных отличий состоит в том, что кортежи можно использовать в качестве ключей в словарях и элементов множеств, а списки - нет. Вот простейший пример:

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print(type(t))
print(d[t])
print(d[(1, 2)])

In [ ]:
# t[0] = 1 # Can't update tuple items

### Функции
Функции Python определяются с помощью ключевого слова `def`. Например:

In [ ]:
def my_function(x):
  a = x + 1
  return a

my_function(3)

In [ ]:
# функция
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

In [ ]:
# её вызов
for y in [-1, 0, 1]:
    print(sign(y))

Мы часто будем создавать функции, принимающие обязательные и необязательные аргументы, например, так:

In [ ]:
def hello(name, loud: bool = False):
    if loud:
        print('HELLO, {}'.format(name.upper()))
    else:
        print('Hello, {}!'.format(name))

hello('Bob')
hello('Fred', loud=True)

### Классы
Синтаксис для определения классов в Python прост:

In [ ]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
          print('HELLO, {}'.format(self.name.upper()))
        else:
          print('Hello, {}!'.format(self.name))

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

### Numpy
NumPy (от Numerical Python) - это основная библиотека для научных вычислений в Python. Она предоставляет дополнительный объект (многомерный массив) и высокопроизводительные инструменты для работы с этими массивами.

Чтобы использовать Numpy, нам сначала нужно импортировать пакет `numpy`:

In [ ]:
import numpy as np

#### Массивы

Массив `numpy` - это сетка значений одного типа, которые индексируются кортежем неотрицательных целых чисел. Количество измерений - это ранг массива; форма массива - это кортеж целых чисел, дающих размер массива по каждому измерению.

Мы можем инициализировать массивы numpy из вложенных списков Python и обращаться к элементам с помощью квадратных скобок:

In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

In [ ]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

`numpy` также предоставляет множество функций для создания массивов:

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

#### Индексы в массивах

Numpy предлагает несколько способов индексирования массивов.

Подобно спискам Python, массивы numpy могут быть нарезаны. Поскольку массивы могут быть многомерными, вы должны указать срез для каждого измерения массива:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

Срез массива - это представление тех же данных, поэтому его изменение приведет к изменению исходного массива:

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

Можно также сочетать целочисленную индексацию с индексацией по срезам. Однако это приведет к получению массива более низкой размерности, чем исходный массив:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

Два способа доступа к данным в средней строке массива выше. Смешивание целочисленной индексации и срезов дает массив более низкой размерности, в то время как использование только срезов дает массив той же размерности, что и исходный массив:

In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

Индексация целочисленных массивов: Когда вы индексируете массивы numpy с помощью нарезки, результирующее представление массива всегда будет подмассивом исходного массива. В отличие от этого, целочисленная индексация массивов позволяет создавать произвольные массивы, используя данные из другого массива. Вот пример:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

Одним из полезных приемов при индексировании целочисленных массивов является выбор или изменение одного элемента из каждой строки матрицы:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

Индексация булевых массивов: Булева индексация массива позволяет выбирать произвольные элементы массива. Часто этот тип индексации используется для выбора элементов массива, удовлетворяющих некоторому условию. Вот пример:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

Для краткости мы опустили много деталей об индексации массивов numpy; если вы хотите узнать больше, вам следует прочитать документацию.

#### Типы данных

Каждый массив numpy - это сетка элементов одного типа. Numpy предоставляет большой набор числовых типов данных, которые вы можете использовать для построения массивов. Numpy пытается угадать тип данных при создании массива, но функции, создающие массивы, обычно включают дополнительный аргумент для явного указания типа данных. Вот пример:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

Вы можете прочитать все о типах данных numpy в [документации](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

#### Операции с массивами

Основные математические функции поэлементно оперируют с массивами и доступны как в виде перегрузки операторов, так и в виде функций в модуле `numpy`:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Обратите внимание, что `*` - это поэлементное умножение, а не умножение матриц. Вместо этого мы используем функцию `dot` для вычисления внутренних произведений векторов, умножения вектора на матрицу и умножения матриц. `dot` доступна как функция в модуле `numpy` и как метод экземпляра объектов массива:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; all produce 219
print(v.dot(w))
print(np.dot(v, w))
print(v @ w)
print(sum([vi * wi for (vi, wi) in zip(v, w)]))

In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

Numpy предоставляет множество полезных функций для выполнения вычислений над массивами; одна из самых полезных - `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

Полный список математических функций, предоставляемых numpy, можно найти в [документации](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Помимо вычисления математических функций с помощью массивов, нам часто требуется изменить форму данных в массивах или иным образом манипулировать ими. Простейшим примером такой операции является транспонирование матрицы; чтобы транспонировать матрицу, просто используйте атрибут T объекта массива:

In [ ]:
print(x)
print("transpose\n", x.T)

In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

#### Broadcasting

Трансляция - это мощный механизм, который позволяет numpy работать с массивами разной формы при выполнении арифметических операций. Часто у нас есть меньший массив и больший массив, и мы хотим использовать меньший массив несколько раз для выполнения некоторой операции над большим массивом.

Например, предположим, что мы хотим добавить постоянный вектор к каждой строке матрицы. Мы можем сделать это следующим образом:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x
# y = np.zeros_like(x)

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

Это работает, но когда матрица `x` очень большая, вычисление явного цикла в Python может быть медленным. Обратите внимание, что добавление вектора `v` к каждой строке матрицы `x` эквивалентно формированию матрицы `vv` путем укладки нескольких копий `v` по вертикали, а затем выполнения поэлементного суммирования `x` и `vv`. Мы можем реализовать этот подход следующим образом:

In [ ]:
print(v)
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

Трансляция в `numpy` позволяет нам выполнить это вычисление без фактического создания нескольких копий `v`. Рассмотрим эту версию, используя трансляцию:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

Строка `y = x + v` работает, даже если `x` имеет форму `(4, 3)`, а `v` имеет форму `(3,)` из-за трансляции; эта строка работает так, как если бы v действительно имела форму `(4, 3)`, где каждая строка была копией `v`, а сумма выполнялась поэлементно.

Трансляция двух массивов вместе следует следующим правилам:

1. Если массивы не имеют одинакового ранга, дополните форму массива более низкого ранга единицами, пока обе формы не будут иметь одинаковую длину.
2. Два массива считаются совместимыми по размерности, если они имеют одинаковый размер в этой размерности или если один из массивов имеет размер 1 в этой размерности.
3. Массивы можно транслировать вместе, если они совместимы во всех измерениях.
4. После трансляции каждый массив ведет себя так, как будто его форма равна поэлементному максимуму форм двух входных массивов.
5. В любом измерении, где один массив имеет размер 1, а другой массив имеет размер больше 1, первый массив ведет себя так, как если бы он был скопирован по этому измерению.

Если это объяснение не имеет смысла, попробуйте прочитать объяснение из [документации](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) или это [объяснение](http://wiki.scipy.org/EricsBroadcastingDoc).

Функции, поддерживающие трансляцию, известны как универсальные функции. Список всех универсальных функций можно найти в [документации](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Вот некоторые применения трансляции:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

Трансляция обычно делает ваш код более лаконичным и быстрым, поэтому вы должны стремиться использовать ее там, где это возможно.

Этот краткий обзор затронул многие важные вещи, которые вам нужно знать о numpy, но он далеко не полный. Обратитесь к [numpy reference](http://docs.scipy.org/doc/numpy/reference/), чтобы узнать о numpy гораздо больше.

### Matplotlib

Matplotlib - это мощная библиотека для построения графиков, гистограмм и прочей визуализации. В этом разделе дается краткое введение в модуль `matplotlib.pyplot`.

Иногда мы будем использовать другие библиотеки для визуализации: Seaborn, Plotly.

Загрузим `matplotlib.pyplot`:

In [ ]:
import matplotlib.pyplot as plt

Для использования в чистой Jupyter-среде (не актуально для Google Colaboratory) вам потребуется выполнить специальную команду `%matplotlib inline`.

#### Графики

Наиболее важной функцией в `matplotlib.pyplot` является `plot`, которая позволяет строить графики двумерных данных. Вот простой пример:

In [ ]:
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)

С помощью небольшой дополнительной работы мы можем легко построить несколько линий одновременно, добавить заголовок, легенду и метки осей:

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])

#### Subplots

С помощью функции `subplot` можно изобразить разные объекты на одном рисунке. Вот пример:

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

plt.figure(figsize=(10,4))

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 2, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

plt.subplot(2, 2, 2)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine2')

plt.subplot(2, 2, 3)

# Make the first plot
plt.plot(x, y_cos)
plt.title('Cosine2')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 2, 4)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

Более подробно о функции `subplot` можно прочитать в [документации](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot).

#### Гистограммы

Для создания одномерной гистограммы нам нужен только один вектор чисел. Для двухмерной гистограммы нам понадобится второй вектор. Ниже мы сгенерируем оба вектора и покажем гистограмму для каждого из них.

In [ ]:
plt.subplots()

In [ ]:
N_points = 100000
n_bins = 20

# Create a random number generator with a fixed seed for reproducibility
rng = np.random.default_rng(19680801)

# Generate two normal distributions
dist1 = rng.standard_normal(N_points)
dist2 = 0.4 * rng.standard_normal(N_points) + 5

fig, axs = plt.subplots(1, 2, sharey=True, tight_layout=True)

# We can set the number of bins with the *bins* keyword argument.
axs[0].hist(dist1, bins=n_bins)
axs[1].hist(dist2, bins=n_bins)

Для построения двумерной гистограммы достаточно иметь два вектора одинаковой длины, соответствующие каждой оси гистограммы.

In [ ]:
fig, ax = plt.subplots(tight_layout=True)
hist = ax.hist2d(dist1, dist2)

Настройка 2D гистограммы аналогична случаю с 1D, вы можете управлять визуальными компонентами, такими как размер бина или цвет.

In [ ]:
from matplotlib import colors

fig, axs = plt.subplots(3, 1, figsize=(5, 15), sharex=True, sharey=True,
                        tight_layout=True)

# We can increase the number of bins on each axis
axs[0].hist2d(dist1, dist2, bins=40)

# As well as define normalization of the colors
axs[1].hist2d(dist1, dist2, bins=40, norm=colors.LogNorm())

# We can also define custom numbers of bins for each axis
axs[2].hist2d(dist1, dist2, bins=(80, 10), norm=colors.LogNorm())

plt.show()

### Pandas

Pandas - это библиотека, предоставляющая такие структуры данных, как `DataFrame` и `Series`, для эффективного хранения таблиц или массивов для быстрой индексации, группировки и обработки. В этом разделе дается краткое введение в ее основные компоненты.

In [ ]:
import pandas as pd

#### Загрузка данных

Объект `pandas.DataFrame` можно создать практически из любого файла, если вы знаете, как в нем разделены строки и столбцы. Можно также создать его из массива `numpy`, а затем вручную назначить имена столбцов:

In [ ]:
%%capture

# Load some csv data
!wget https://raw.githubusercontent.com/hse-ppmm/Seminars/main/titanic.csv
# And some plain .data files with columns specified in .names
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.names
# Create some numpy array
sm_arr = np.random.randn(150, 3)

In [ ]:
# Read csv data. Note the `sep` argument - it tells `pandas` how to split lines
# csv_data = pd.read_csv("titanic.csv", sep=',')
# или
csv_data = pd.read_csv("https://raw.githubusercontent.com/hse-ppmm/Seminars/main/titanic.csv", sep=',')
# Show top 5 rows of data
csv_data.head(5)

In [ ]:
# Read .data file that contains features of Iris dataset.
# Note that column names are not provided - so we set header=None
# (Otherwise it treats the first row as column names)
ord_data = pd.read_table("iris.data", sep=',', header=None)
# Assign column names manually
ord_data.columns = [
                    "sepal length", "sepal width",
                    "petal length", "petal width", "class"
]
# Shift row index by 3
ord_data.index = [v + 3 for v in ord_data.index]
# Show last 4 samples
ord_data.tail(4)

In [ ]:
# Read numpy array and assign random column names
arr_data = pd.DataFrame(
    sm_arr,
    columns=["feature " + str(i) for i in range(3)]
)
# One-dimensional arrays can be converted to Series
arr_flat_data = pd.Series(sm_arr[:,0])
# Get shapes
arr_data.shape, arr_flat_data.shape

#### Индексы в DataFrame

Аналогично `python`, `pandas` использует ссылочные переменные для классов `DataFrame` и `Series` для экономии памяти. Он также поддерживает большую часть `numpy`-подобной индексации. Кроме того, мы можем получить доступ к их содержимому с помощью методов `.loc` и `.iloc`, а также итерировать их с помощью методов `.iterrows` и `.iteritems`:

In [ ]:
# Use sm condition to filter rows
cond_data = ord_data.loc[ord_data["sepal length"] > 7.0]
cond_data.sample(7)

In [ ]:
# Or specify desired indices
cond_data = ord_data.iloc[105:110, :]
cond_data.head()

In [ ]:
# Replace sepal length values of 7.3 to 9.2
for idx, line in cond_data.iterrows():
    if line["sepal length"] == 7.3:
        cond_data.loc[idx, "sepal length"] = 9.2

cond_data.iloc[1:4, 0] # SettingWithCopyWarning

Обратите внимание на предупреждение. И `cond_data`, и `ord_data` являются ссылками, указывающими на одно и то же пространство, поэтому обновление содержимого `cond_data` через `.loc` автоматически обновит содержимое `ord_data`. Мы можем исправить это, используя метод `.copy`:

In [ ]:
# More advanced version - drop inefficient `for` looping with a `where` method,
# then copy it
cond_data_2 = cond_data.where(cond_data["sepal width"] != 7.3, 9.2).copy()
cond_data_2.loc[:, "petal length"] = 10.0

cond_data_2.sample(3, random_state=0)

In [ ]:
# Original data left unmodified
cond_data.sample(3, random_state=0)

In [ ]:
cond_data.describe()

#### Визуализация

Библиотека `pandas` предоставляет несколько методов визуализации, такие как `boxplot` и `scatter_matrix`:

In [ ]:
# Visualize mean/std and quantiles for interval values
# Ignores all non-interval values (e.g. 'classes')
pd.plotting.boxplot(
    ord_data,
    grid=True
)
plt.show()

In [ ]:
# Plot grid of pairwise scatterplots (histograms for diagonal values)
pd.plotting.scatter_matrix(
    # Select only some columns
    ord_data[['petal length', 'petal width', 'sepal length']],
    grid=True
)
plt.show()

Больше инструментов предоставляется в пакетах `matplotlib` и `seaborn`, которые поддерживают объекты `pandas`.

#### Статистика

`pandas` предоставляет несколько полезных методов для изучения статистики признаков:

In [ ]:
# `count` row describes number of nonNA feature values in column,
# 25%, 50%, 75% shows respective percentiles
csv_data.describe()

In [ ]:
# Any nan values in columns?
csv_data.isna().any()

In [ ]:
# Pairwise correlations btwn column features
csv_data[['Age', 'Fare', 'Survived']].corr()

In [ ]:
# Get amounts of unique values for categorical feature and show it in hist
csv_data['Pclass'].value_counts().plot(kind='bar')
plt.show()

In [ ]:
csv_data['Survived'].value_counts().plot(kind='bar')

In [ ]:
# plt.hist(csv_data['Pclass'])

In [ ]:
csv_data.head()

In [ ]:
csv_data.iloc[0, :]['Name']

In [ ]:
# Extract all surnames of passengers and count unique instances
csv_data.apply(lambda row: row['Name'].split(',')[0], axis=1).unique().shape

In [ ]:
# Highlight larger pairwise correlations with color
csv_data.corr().style.background_gradient()

### Работа со случайными числами

In [ ]:
import numpy as np
import numpy.random

In [ ]:
# numpy.random.seed(42)

# x = numpy.random.normal(2.0, 1.0, 1000)
# print(x.shape)
# print(np.mean(x))
# print(np.var(x))
# print()

# x = numpy.random.normal(np.arange(4).reshape(2,2), 1.0, (1000,2,2))
# print(x.shape)
# print(np.mean(x, axis=0))
# print(np.var(x, axis=0))
# print()

x = numpy.random.normal(3.0, 1.0, 100000)
_ = plt.hist(x,250)
print(np.mean(x))
print(np.var(x))

In [ ]:
# plt.hist2d(x[0,:],x[1,:])

In [ ]:
# numpy.random.seed(42)

x = numpy.random.poisson(6.0, 10000)
print(np.mean(x))
print(np.var(x))
_ = plt.hist(x,25)

# Разведочный анализ данных

EDA, Exploratory Data Analysis

<img src="http://sharpsightlabs.com/wp-content/uploads/2016/05/1_data-analysis-for-ML_how-we-use-dataAnalysis_2016-05-16.png" />

In [ ]:
# Датасет https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data
# Примеры из курса https://www.hse.ru/edu/courses/450323352
data = pd.read_csv('https://raw.githubusercontent.com/hse-ppmm/Seminars/main/house-pricing-train.csv')

In [ ]:
data.head(10)

In [ ]:
data.shape

In [ ]:
data.info()

## Что делать с пропущенными записями?

In [ ]:
data.describe(include='all')

#### Убрать признаки с неполным количеством записей?

In [ ]:
columns_to_drop = ['LotFrontage', 'FireplaceQu', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond']
data.drop(columns=columns_to_drop, inplace=True),
data.shape

#### Как распределена целевая переменная?

Целевым признаком является `SalePrice`.

Есть ли у него пропущенные значения.
Как оно распределено?
Есть ли выбросы?

Постройте график распределения (гистограмму), чтобы ответить на эти вопросы.

In [ ]:
print(data['SalePrice'].describe())
plt.figure(figsize=(8, 6))
plt.hist(data['SalePrice']);

### Числовые данные

In [ ]:
list(set(data.dtypes.tolist()))

In [ ]:
df_num = data.select_dtypes(include = ['float64', 'int64'])
df_num.shape

In [ ]:
df_num.hist(figsize=(16, 20), bins=50, xlabelsize=8, ylabelsize=8);

### Корреляции

In [ ]:
df_num_corr = df_num.corr() # Корреляционная матрица
df_num_corr = df_num_corr['SalePrice'][:-1] # Рассмотрим корреляции к переменной SalePrice за исключением её самой
df_num_corr[:10]

In [ ]:
golden_features_list = list(df_num_corr[abs(df_num_corr) >= 0.5].index)
print("There is {} strongly correlated values with SalePrice:\n{}".format(len(golden_features_list), golden_features_list))

In [ ]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import seaborn as sns
sns.set()

for i in range(0, len(df_num.columns), 5):
    sns.pairplot(data=df_num,
                x_vars=df_num.columns[i:i+5],
                y_vars=['SalePrice'])

In [ ]:
# sns.pairplot(data)

### Категорийные переменные

In [ ]:
df_cat = data.select_dtypes(include = ['O'])
df_cat.head()

In [ ]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import seaborn as sns
feature = 'KitchenQual'
unique_values = set(data[feature].values)
plt.figure(figsize=(10, 7))
for value in unique_values:
    sns.distplot(data[data[feature] == value]['SalePrice'], label=f'{feature} = {value}')
tmp = plt.legend()
tmp = plt.show()

In [ ]:
corr = df_num.drop('SalePrice', axis=1).corr()
plt.figure(figsize=(12, 10))

sns.heatmap(corr[(corr >= 0.5) | (corr <= -0.4)],
            cmap='viridis', vmax=1.0, vmin=-1.0, linewidths=0.1,
            annot=True, annot_kws={"size": 8}, square=True);